# ???? Spring Boot ???????
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
  org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration,\
  org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

nacos.server.main.port=8848

spring.sql.init.platform=mysql
# Count of DB:
db.num=1
db.url.0=jdbc:mysql://127.0.0.1:3306/ai-service-nacos?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
db.user=root
db.password=123456

management.elastic.metrics.export.enabled=false

management.influx.metrics.export.enabled=false

address.server.domain=127.0.0.1
server.address=0.0.0.0

nacos.config.push.maxRetryTime=50

nacos.naming.empty-service.auto-clean=true
nacos.naming.empty-service.clean.initial-delay-ms=50000
nacos.naming.empty-service.clean.period-time-ms=30000

nacos.ai.mcp.registry.port=9080

nacos.server.contextPath=/nacos

server.tomcat.accesslog.enabled=true

server.tomcat.accesslog.max-days=30

server.tomcat.accesslog.pattern=%h %l %u %t "%r" %s %b %D %{User-Agent}i %{Request-Source}i

### The directory of access log:
server.tomcat.basedir=file:.

server.error.include-message=ALWAYS

nacos.console.port=8849
nacos.console.contextPath=/nacos

nacos.console.remote.server.context-path=/nacos
nacos.console.ui.enabled=true
nacos.cmdb.dumpTaskInterval=3600

nacos.security.ignore.urls=/,/error,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-ui/public/**,/v1/auth/**,/v1/console/health/**,/actuator/**,/v1/console/server/**

nacos.core.auth.system.type=nacos

nacos.core.auth.enabled=false
nacos.core.auth.admin.enabled=false
nacos.core.auth.console.enabled=false

nacos.core.auth.caching.enabled=false

nacos.core.auth.server.identity.key=nacos
nacos.core.auth.server.identity.value=nacos

nacos.core.auth.plugin.nacos.token.cache.enable=false
nacos.core.auth.plugin.nacos.token.expire.seconds=18000
nacos.core.auth.plugin.nacos.token.secret.key=VGhpc0lzTXlDdXN0b21TZWNyZXRLZXkwMTIzNDU2Nzg=

nacos.istio.mcp.server.enabled=false

nacos.k8s.sync.enabled=false

nacos.config.fuzzy.watch.max.pattern.count=20
nacos.config.fuzzy.watch.max.pattern.match.config.count=500

nacos.naming.fuzzy.watch.max.pattern.count=20
nacos.naming.fuzzy.watch.max.pattern.match.service.count=500