# =========================================================
# nova-auth 专属（端口 / 邮件验证码）
# 复制到 Nacos：DataId = nova-auth-dev.yml
# =========================================================
server:
  port: 9000

nova:
  mail:
    enabled: true
    account:
      host: smtp.163.com
      port: 465
      auth: true
      sslEnable: true
      from: wuzhixin666@163.com
      user: wuzhixin666@163.com
      pass: RVe5VbNd2KLpnHCL
  auth:
    email-code:
      expire-minutes: 5
      retry-seconds: 60
      length: 6
      title: NovaCloud 验证码

logging:
  level:
    com.nova: info
