# =========================================================
# nova-system 专属（端口等）
# 复制到 Nacos：DataId = nova-system-dev.yml
# =========================================================
server:
  port: 8081

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
      - org.apache.rocketmq.spring.autoconfigure.RocketMQAutoConfiguration

logging:
  level:
    com.nova: info
