# =========================================================
# nova-gateway 专属（端口 / 路由 / 网关鉴权 / 国密）
# 复制到 Nacos：DataId = nova-gateway-dev.yml
# =========================================================
server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: nova-auth
          uri: lb://nova-auth
          predicates:
            - Path=/auth/**,/oauth2/**,/.well-known/**
        - id: nova-system
          uri: lb://nova-system
          predicates:
            - Path=/system/**
        - id: nova-file
          uri: lb://nova-file
          predicates:
            - Path=/file/**
        - id: nova-demo
          uri: lb://nova-demo
          predicates:
            - Path=/demo/**
        - id: nova-ai
          uri: lb://nova-ai-server
          predicates:
            - Path=/ai/**

nova:
  gateway:
    auth:
      enabled: true
      white-list:
        - /auth/**
        - /oauth2/**
        - /.well-known/**
        - /actuator/**
        - /v3/api-docs/**
        - /swagger-ui/**
        - /swagger-ui.html
  crypto:
    enabled: false
    sm4-key: NovaCloudSm4Key!
    sm3-salt: NovaCloudSm3Salt
    encrypt-header: X-Nova-Encrypt
    sign-header: X-Nova-Sign
    timestamp-header: X-Nova-Timestamp

logging:
  level:
    com.nova: info
