# =========================================================
# 对齐 nova-auth：只用 spring.config.import 拉 Nacos
# nacos.namespace 必须填命名空间 ID（不能填显示名称 nova-cloud）
# =========================================================
spring:
  application:
    name: nova-gateway
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  cloud:
    nacos:
      # 免密保持注释
#      username: ${NACOS_USERNAME:nacos}
#      password: ${NACOS_PASSWORD:nacos}
      server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      discovery:
        enabled: true
        namespace: ${NACOS_NAMESPACE:bd3454be-a672-433f-a1da-97f1d0ce8038}
        group: DEFAULT_GROUP
      config:
        enabled: true
        namespace: ${NACOS_NAMESPACE:bd3454be-a672-433f-a1da-97f1d0ce8038}
        group: DEFAULT_GROUP
        file-extension: yml
        refresh-enabled: true
  config:
    import:
      - nacos:${spring.application.name}-dev.yml?group=DEFAULT_GROUP&refreshEnabled=true
      - nacos:application-common.yml?group=DEFAULT_GROUP&refreshEnabled=true
      - nacos:application-security.yml?group=DEFAULT_GROUP&refreshEnabled=true
