# =========================================================
# 本服务专属（开发环境）
# 复制到 Nacos：DataId = nova-demo-dev.yml
# =========================================================
server:
  port: 8090

logging:
  level:
    com.nova: info
    com.nova.mq: debug
    com.nova.demo.mq: debug
    org.apache.shardingsphere: info
