<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.nova</groupId>
        <artifactId>nova-cloud</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>nova-visual</artifactId>
    <packaging>pom</packaging>
    <description>可视化组件：Spring Boot Admin 监控、Sentinel 控制台</description>

    <modules>
        <module>nova-monitor</module>
        <module>nova-sentinel</module>
    </modules>
</project>
